### ISSUE TITLE
Research NestJs

### ISSUE THREAD

**Issue by hungnp194** [zinza-d2-training/haoth-nestjs#1]
- [ ] Controller
- [ ] Provider
- [ ] Middleware
- [ ] Authentication
- [ ] Multiple Auth (Guard)
- [ ] Validation (pipe - dto)
- [ ] Interceptor
- [ ] Custom decorations
- [ ] Database typeorm

**Yêu cầu:**

- [ ] Init project
- [ ] Kết nối Mysql bằng Typeorm
- [ ] DB có bảng user
- [ ] Tạo API danh sách user, thêm sửa xóa và chạy = PostMan
- [ ] Có validate (DTO)

**Comment by tahuuhao** [comment]
[Init Project](https://github.com/zinza-d2-training/haoth-nestjs/commits/master)
Tìm hiểu Controller, Provider, Middleware, Validation, cài đặt PostMan, MySQL
